FROM node:16-alpine as ts-compiler
RUN mkdir -p /home/node/app/node_modules && chown -R node:node /home/node/app
WORKDIR /home/node/app
COPY package*.json ./
COPY tsconfig*.json ./
COPY prisma ./prisma/
RUN npm install
# RUN npm install -g typescript
RUN npx prisma generate
COPY --chown=node:node . .
EXPOSE 3000
RUN npm run build
CMD [ "node", "./src/server.ts" ]